name: ci
concurrency:
  group: publish-${{ github.github.base_ref }}
  cancel-in-progress: true
on: [push]
jobs:
  publish:
    name: "Publish Module to NPM"
    if: github.repository == 'tanstack/react-table')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      # - uses: jwalton/gh-find-current-pr@v1
      #   id: findPr
      #   with:
      #     state: open
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          git config --global user.name 'Tanner Linsley'
          git config --global user.email 'tannerlinsley@users.noreply.github.com'
          yarn cipublish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YARN_REGISTRY: https://registry.npmjs.org/
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          # GH_TOKEN: ${{secrets.GH_TOKEN}}
