name: ci
concurrency:
  group: publish-${{ github.github.base_ref }}
  cancel-in-progress: true
on: [push]
jobs:
  test-and-publish:
    name: "Test & Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          git config --global user.name 'Tanner Linsley'
          git config --global user.email 'tannerlinsley@users.noreply.github.com'
          yarn cipublish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YARN_REGISTRY: https://registry.npmjs.org/
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
