name: pr
on: [pull_request]
jobs:
  test:
    name: 'Test (node ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
          npm run build
          npm run test
