name: 'Close stale issues'
on:
  workflow_dispatch:
    branches:
      - alpha

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          stale-issue-message: 'This issue is being marked as stale (no activity in the last 14 days)'
          stale-pr-message: 'This pull request is being marked as stale (no activity in the last 14 days)'
          close-pr-message: |
            This pull request has been detected as stale (no activity in the last 14 days) and automatically closed. It's very likely that your pull request has remained here this long because it introduces breaking changes to the v7 API. **React Table v8** is currently in alpha (soon beta!) and already contains bug fixes, performance improvements and architectural changes that likely address the issue this pull request is meant to solve.

            - If your v7 pull request has been previously labeled as having breaking changes, please try the new v8 alpha/beta releases
            - If your v7 pull request **has not already been labeled as a breaking change**, open a new pull request.
            - If this was a v8 pull request and was closed by mistake, please reopen or leave a comment below.
          close-issue-message: |
            This issue has been detected as stale and automatically closed. It's very likely that your issue has remained here this long because it would require breaking changes to v7. **React Table v8** is currently in alpha (soon beta!) and already contains bug fixes, performance improvements and architectural changes that likely address this issue.

            - If your v7 issue has been previously labeled as requiring breaking changes, please try the new v8 alpha/beta releases
            - If your v7 issue **has not already been labeled as a breaking change**, open a new issue.
            - If this was a v8 issue and was closed by mistake, please reopen or leave a comment below.
