name: 'Close stale issues'
on:
  workflow_dispatch:
    branches:
      - alpha

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 10000000
          days-before-close: 14
          stale-issue-message: 'This issue is being closed as stale'
          close-issue-message: |
            This issue has been detected as stale (no activity in the last 14 days) and automatically closed. It's very likely that your issue has remained here this long because it would require breaking changes to v7. **React Table v8** is currently in alpha (soon beta!) and already contains bug fixes, performance improvements and architectural changes that likely address this issue.

            - If your v7 issue has been previously labeled as requiring breaking changes, please try the new v8 alpha/beta releases
            - If your v7 issue **has not already been labeled as a breaking change**, open a new issue.
            - If this was a v8 issue and was closed by mistake, please reopen or leave a comment below.
